### ISSUE TITLE
Hope a implementation key load and key save to file

### ISSUE THREAD

**Issue by SamYuan1990** [Hyperledger-TWGC/Gm-Go#15]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
https://github.com/Hyperledger-TWGC/pku-gm/blob/master/gmssl/engine.go#L85-L87

**Describe the solution you'd like**
Having implementation to load key from file.
Having implementation to write key into file.

**Describe alternatives you've considered**
If we using this one to implementation for a bccsp, we need able to R/W key from file.
There is one thing I am not ensure should we implements key load in this level or not.
Ref:
https://github.com/hyperledger/fabric/blob/master/bccsp/sw/fileks.go#L259-L273

From another point of consideration, we need to test the key generate by this project with a nodejs implementation(for nodejs sdk). In that case, we will also able to write the structure below from memory into files.
https://github.com/Hyperledger-TWGC/pku-gm/blob/master/gmssl/pkey.go#L629-L635

**Additional context**
N/A

**Comment by davidkhala** [comment]
@zhaoxiaomeng 有可能提供一个pem格式的私钥么？

**Comment by zxm256** [comment]
可以通过NewPrivateKeyFromPEM 从一个字符串（pem）格式导入私钥。通过NewPublicKeyFromPEM导入公钥
通过func (pk *PublicKey) GetPEM() 导出公钥，func (sk *PrivateKey) GetPEM导出私钥

**Comment by davidkhala** [comment]
发现Private Key导出PEM的函数不允许填入空pass。有可能允许不加密处理么？

**Comment by zxm256** [comment]
在pr #19 中进行了修改，可以允许不加密导出私有，虽然不是很建议使用这种方式（非常不安全）

**Comment by davidkhala** [comment]
@zhaoxiaomeng Fabric的SW现在就是在各处采用了这种不加密的PEM格式

**Comment by davidkhala** [comment]
测试了了pku-gm的私钥无加密导出成为pem格式后，在tjfoc-gm中读取没有格式上的错误

**Comment by davidkhala** [comment]
resolved in https://github.com/Hyperledger-TWGC/GM-interoperability
