### ISSUE TITLE
SMS4 ECB 模式

### ISSUE THREAD

**Issue by davidkhala** [Hyperledger-TWGC/Gm-Go#16]
**Is your feature request related to a problem? Please describe.**
现在go接口只有SMS4 CBC模式，需要同时提供key和IV

**Describe the solution you'd like**

希望能添加SMS4 ECB模式的 Go 语言API

**Describe alternatives you've considered**
ECB模式实际上是对于一个分组来做的，实际上用处不大，而且安全性不高，一般很少用这个模式了

**Additional context**
linked issues:
https://github.com/guanzhi/GmSSL/issues/523

**Comment by zxm256** [comment]
已经增加了 ECB 模式 #18
