### ISSUE TITLE
需要SM4支持

### ISSUE THREAD

**Issue by davidkhala** [Hyperledger-TWGC/Gm-Go#23]
**Is your feature request related to a problem? Please describe.**
- We see `FIXME: PKCS #5 can not use SM4`

**Describe the solution you'd like**
- Provide SM4 go interface for gmssl, since it is already implemented in gmssl C++

**Comment by zxm256** [comment]
@davidkhala  不好意思最近有点忙没来得及及看github，目前应该是已经有了SM4了呀，在test中有ECB和CBC的测试代码，是希望单独做成一个函数么？
