### ISSUE TITLE
Unused parameter `eng *Engine` in GeneratePrivateKey

### ISSUE THREAD

**Issue by davidkhala** [Hyperledger-TWGC/Gm-Go#8]
https://github.com/Hyperledger-TWGC/Gm-Go/blob/c544e7e85b5d3563eafb89b52eed54e3e333045e/gmssl/pkey.go#L644

I see some lines of codes are commented here. 
Why it was here and why it is now not used?

**Comment by zxm256** [comment]
Fix this in new pull request
